### ISSUE TITLE
Moves interface definition to inc

### ISSUE THREAD

**Issue by chillfig** [nasa/ci_lab#133]
**Is your feature request related to a problem? Please describe.**
The interface definition files of all open source apps currently exist in the "src" directory.

**Describe the solution you'd like**
Create an "inc" dir to go with the "src" dir.  Move the interface definitions into this location: "_msg.h", "_msgdefs.h", "_tbldefs.h", and "_events.h". Consider moving header files in both "platform_inc" and "mission_inc" to "inc"

**Describe alternatives you've considered**
Leaving as is.

**Additional context**
N/A

**Requester Info**
Justin Figueroa, Vantage Systems

**Comment by skliper** [comment]
@dzbaker - should this be closed?  I think #147 and #148 covered it.

**Comment by dzbaker** [comment]
Covered by #147, #148.
