### ISSUE TITLE
Split out ci_lab platform config from app header

### ISSUE THREAD

**Issue by skliper** [nasa/ci_lab#2]
Originated by abrown4 (59 on babelfish):

The platform-specific config (that I need to change for a deployment) is in the ci_lab_app.h, and thus common to all ci_lab builds. However, I want to build and deploy multiple cfs instances, each with a ci_lab. [It _is_ simple and handy.]
Propose moving the platform-specific info into ci_lab_platform_cfg.h, like the other apps.

**Comment by skliper** [comment]
Note original issue has a changeset, need to create patch and apply here.

**Comment by skliper** [comment]
@dzbaker - should this be closed per #148 and #147?

**Comment by dzbaker** [comment]
Covered by #147, #148.
