### ISSUE TITLE
Update to use OSAL socket API

### ISSUE THREAD

**Issue by skliper** [nasa/ci_lab#23]
**Is your feature request related to a problem? Please describe.**
Currently uses cFE supplied network_includes.h and not the abstracted OSAL calls

**Describe the solution you'd like**
Update to use OSAL

**Describe alternatives you've considered**
None

**Additional context**
See osapi-os-net.h and/or OSAL API.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Note: This is already implemented in the EDS branch (techdev-sois-eds on babelfish).  In here the CI_LAB and TO_LAB use the socket abstraction via OSAL.

It probably wouldn't be too difficult to separate the changes, and make a non-EDS CI_LAB/TO_LAB, if necessary.

**Comment by jphickey** [comment]
Backporting this change from the EDS branch
