### ISSUE TITLE
Check message length vs bytes received before publishing

### ISSUE THREAD

**Issue by skliper** [nasa/ci_lab#64]
**Is your feature request related to a problem? Please describe.**
Command ingest doesn't verify message length (from header) matches bytes received.

**Describe the solution you'd like**
Verify prior to publishing to SB (stop the error at the source).

**Describe alternatives you've considered**
Leave as is - command sources should be sending one valid message per datagram

**Additional context**
None.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
@dzbaker @jphickey - looks like this was also fixed:
https://github.com/nasa/ci_lab/blob/6e55bb4b98b707d6eeccbd4e70ec376a3cc0ba98/fsw/src/ci_lab_passthru_decode.c#L92-L108

Close?

**Comment by dzbaker** [comment]
Resolved by #152.
